# Generated by Django 3.0.1 on 2019-12-26 03:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_id', models.TextField()),
                ('splitwise_id', models.TextField()),
            ],
        ),
    ]
