# Generated by Django 3.0.1 on 2020-01-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200109_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojimatch',
            name='first_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emojimatch',
            name='second_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
