# Generated by Django 3.0.1 on 2020-01-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200109_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojimatch',
            name='tied',
            field=models.BooleanField(default=False),
        ),
    ]
