# Generated by Django 3.0.2 on 2020-01-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emojimatch_tied'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
