# Generated by Django 3.0.2 on 2020-02-01 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200130_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojimatch',
            name='first_voters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emojimatch',
            name='second_voters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
            preserve_default=False,
        ),
    ]
